#!/bin/bash
#
# Scans Submissions/ for ClipExperience conformances and generates SubmissionRegistry.swift.
# Added as an Xcode Run Script Build Phase so the registry updates every build.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

SUBMISSIONS_DIR="$ROOT_DIR/Submissions"
OUTPUT_FILE="$ROOT_DIR/ReactivChallengeKit/ReactivChallengeKit/SubmissionRegistry.swift"

TYPES=()

if [ -d "$SUBMISSIONS_DIR" ]; then
    while IFS= read -r line; do
        type_name=$(echo "$line" | sed -E 's/.*struct[[:space:]]+([A-Za-z0-9_]+)[[:space:]]*:.*/\1/')
        if [ -n "$type_name" ]; then
            TYPES+=("$type_name")
        fi
    done < <(grep -r --include="*.swift" 'struct[[:space:]]\+[A-Za-z0-9_]*[[:space:]]*:.*ClipExperience' "$SUBMISSIONS_DIR" 2>/dev/null || true)
fi

{
    echo "/// Auto-generated by scripts/generate-registry.sh — do not edit manually."
    echo "/// Run the build or execute the script to regenerate after adding submissions."
    echo "enum SubmissionRegistry {"
    echo "    static let all: [any ClipExperience.Type] = ["

    for type in "${TYPES[@]}"; do
        echo "        ${type}.self,"
    done

    echo "    ]"
    echo "}"
} > "$OUTPUT_FILE"

echo "SubmissionRegistry: found ${#TYPES[@]} submission(s)"
